#!/usr/bin/env python2

import Tkinter as tk
# themed tk
import ttk
import tkFont
import ttt

WIDTH = 750
HEIGHT = 800
PLAYER_LABELS = {1:'X', -1:'O', 0:''}

''' This GUI uses game logic in ttt directly; no networking involved'''        

# TODO: need to schedule events in the Tkinter main loop, call after()

class TkTictactoe(ttk.Frame):

    def __init__(self, master = None):
        ttk.Frame.__init__(self, master, width=WIDTH, height=HEIGHT)
        
        self.game = ttt.TicTacToeGame()
        self.gameswon = 0
        self.gameslost = 0

        # don't shrink the frame to its content
        self.grid_propagate(False)

        # draw the frame (and its content); make all the edges of the frame
        # stick to the edges of the root window
        self.grid(sticky=tk.NSEW)
        # All the board buttons should expand if the main window is resized
        # We achieve this by giving w/h of the cells on the diagonal the same
        # "expansion" weight
        self.columnconfigure(0, weight=1)
        self.rowconfigure(0, weight=1)
        self.columnconfigure(1, weight=1)
        self.rowconfigure(1, weight=1)
        self.columnconfigure(2, weight=1)
        self.rowconfigure(2, weight=1)
        self.place_widgets()
        

    def place_widgets(self):
        # game buttons
        self.board = [[tk.Button(self, font=tkFont.Font(size=60), fg='black')  
                       for i in range(3)] for i in range(3)]
        for rownum, row in enumerate(self.board):
            for colnum, button in enumerate(row):
                name = str(rownum) + ',' + str(colnum)
                button.grid(column=colnum, row=rownum, sticky=tk.NSEW)
                button.bind("<Button-1>", self.record_move)
    
        # menu
        self.quit_btn = ttk.Button(self, text='Exit', command=self.quit)
        self.quit_btn.grid(column=2, row=4, pady=10)
        self.newgame_btn = ttk.Button(self, text='New Game', 
                                      command=self.start_new_game)
        self.newgame_btn.grid(column=2, row=3, pady=10)

        # status
        self.glostlbl = ttk.Label(self, text="Games Lost: 0")
        self.glostlbl.grid(column=1, row=3)
        self.gwonlbl = ttk.Label(self, text="Games Won: 0")
        self.gwonlbl.grid(column=0, row=3)
        
    def quit(self):
        # TODO: disconnect
        self.master.quit()

    def record_move(self, event):
        ''' process human move '''
        #if game not over
        if self.game.mode >= 3:
            if event.widget['text'] == '':
                player = self.game.current_player
                player_repr = PLAYER_LABELS[player]
                self.game.make_move(player, self.find_button_coords(event.widget))
                event.widget['text'] = player_repr
                # check for game over each time make_move is called
                if self.game.mode <= 2:
                    self.cleanup()
                self.record_computer_move()
                
    def record_computer_move(self):
        ''' process move generated by super fancy game ai'''
        # if game not over
        if self.game.mode >= 3:
            player = self.game.current_player
            player_repr = PLAYER_LABELS[player]
            (row, col) = self.game.make_random_move(player)
            self.board[row][col]['text'] = player_repr
            # check for game over each time make_move is called
            if self.game.mode <= 2:
                self.cleanup()
    
    def cleanup(self):
        ''' update/reset after finished game '''
        
        mode = self.game.mode

        if mode == ttt.GSTATES['P1WON']:
            self.gameswon += 1
            print "Won: %s" % self.gameswon
            self.update_game_count_lbl(self.gwonlbl, self.gameswon)
        elif mode == ttt.GSTATES['P2WON']:
            self.gameslost += 1
            print "Lost: %s" % self.gameslost 
            self.update_game_count_lbl(self.glostlbl, self.gameslost)

        if mode < 2: # X won or O won
            for (row,col) in self.game.lastwincoords:
                self.board[row][col].configure(fg="red")        

    def start_new_game(self):
        if self.game.mode == ttt.GSTATES['INPROGRESS']:
            self.gameslost += 1 
            self.update_game_count_lbl(self.glostlbl, self.gameslost)
        self.game = ttt.TicTacToeGame()
        # reset the buttons
        for row in self.board:
            for b in row:  
                b['text'] = ''
                b['fg'] = 'black'

    def update_game_count_lbl(self, label, newcount):
        ltext = label['text']
        label['text'] = (ltext[:ltext.rindex(':') + 1] +
                        str(newcount))

    def find_button_coords(self, button):
        # This sucks. I don't know how to associate a button with an id in tk
        # but it seems impossible
        for r,row in enumerate(self.board):
            for c,b in enumerate(row):
                if b is button:
                    return (r,c)

        raise Exception("Button not found!")
    

# puts the Tktictactoe frame in main root window
if __name__ == "__main__":
    root = tk.Tk()
    # the window content should expand if the main window is resized
    root.grid_columnconfigure(0, weight=1)
    root.grid_rowconfigure(0, weight=1)
    gameframe = TkTictactoe(master = root)

    root.title("Tic Tac Toe!")
    root.mainloop()
    


    
